from PyQt6.QtWidgets import QWidget, QHBoxLayout, QVBoxLayout, QLabel, QPushButton, QGridLayout, QTableWidget, QHeaderView
from PyQt6.QtCore import Qt

def create_game_ui(game):
    widget = QWidget()
    layout = QHBoxLayout()
    left = QVBoxLayout()
    game.info_label = QLabel("")
    game.score_label = QLabel("301")
    game.score_label.setStyleSheet("font-size: 90px; font-weight: bold; color: #3daee9;")
    game.dart_label = QLabel("Darts: ○ ○ ○")
    left.addWidget(game.info_label); left.addWidget(game.score_label); left.addWidget(game.dart_label)
    mod_layout = QHBoxLayout()
    game.btn_double = QPushButton("DOUBLE (D)"); game.btn_triple = QPushButton("TRIPLE (T)")
    for b in [game.btn_double, game.btn_triple]:
        b.setCheckable(True)
        b.setStyleSheet("QPushButton:checked { background-color: #27ae60; border: 1px solid white; }")
        b.clicked.connect(game.mod_clicked)
        mod_layout.addWidget(b); game.num_buttons.append(b)
    left.addLayout(mod_layout)
    grid = QGridLayout()
    for i in range(1, 21):
        btn = QPushButton(str(i)); btn.setFixedSize(60, 50)
        btn.clicked.connect(lambda ch, v=i: game.num_clicked(v))
        grid.addWidget(btn, (i-1)//7, (i-1)%7); game.num_buttons.append(btn)
    btn_zero = QPushButton("0")
    btn_zero.setFixedSize(60, 50)
    btn_zero.setStyleSheet("background-color: #5d6368; font-weight: bold;")
    btn_zero.clicked.connect(lambda: game.num_clicked(0))
    grid.addWidget(btn_zero, 2, 6); game.num_buttons.append(btn_zero)
    left.addLayout(grid)
    spec = QHBoxLayout()
    btn_25 = QPushButton("BULL")
    btn_25.setStyleSheet("background-color: #454a4f; height: 50px; font-weight: bold;")
    btn_25.clicked.connect(lambda: game.num_clicked(25))
    btn_bullseye = QPushButton("BULLSEYE")
    btn_bullseye.setStyleSheet("background-color: #454a4f; height: 50px; font-weight: bold;")
    btn_bullseye.clicked.connect(game.hit_bullseye)
    spec.addWidget(btn_25); spec.addWidget(btn_bullseye)
    game.num_buttons.extend([btn_25, btn_bullseye])
    left.addLayout(spec)
    ctrl = QHBoxLayout()
    undo_btn = QPushButton("Korrektur (Back)")
    undo_btn.setStyleSheet("QPushButton { background-color: #fdbc4b; color: black; font-weight: bold; height: 35px; } QPushButton:disabled { background-color: #554422; color: #888888; }")
    undo_btn.clicked.connect(game.undo_hit)
    game.back_btn = QPushButton("Abbrechen")
    game.back_btn.setStyleSheet("background-color: #454a4f; height: 35px;")
    game.back_btn.clicked.connect(game.cancel_game)
    ctrl.addWidget(undo_btn); ctrl.addWidget(game.back_btn)
    game.num_buttons.extend([undo_btn, game.back_btn])
    left.addLayout(ctrl)
    layout.addLayout(left, 3)
    game.table = QTableWidget()
    game.table.setColumnCount(3)
    game.table.setHorizontalHeaderLabels(["Spieler", "Letzte Würfe", "Score"])
    game.table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
    game.table.setFocusPolicy(Qt.FocusPolicy.NoFocus)
    game.table.setSelectionMode(QTableWidget.SelectionMode.NoSelection)
    game.table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
    layout.addWidget(game.table, 2)
    widget.setLayout(layout)
    return widget
